services:
  web:
    build: .
    ports:
      - "8000:8000"
    container_name: web
    restart: always
    networks:
      - web_network

  postgres:
    image: postgres
    container_name: mydb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
      POSTGRES_DB: hw02
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - web_network

networks:
  web_network:
    driver: bridge

volumes:
  pgdata: