services:
  web:
    build: .
    ports:
      - "3000:3000"
    container_name: web
    restart: always
    volumes:
      - ./storage:/app/storage
    networks:
      - web_network

networks:
  web_network:
    driver: bridge

volumes:
  storage: